SET SQL_SAFE_UPDATES=0;
DROP DATABASE IF EXISTS playlists;

CREATE DATABASE playlists;

USE playlists;
-- todo: remove the user table
CREATE TABLE Users (
  UserID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  PasswordHash VARCHAR(50) NOT NULL
);

CREATE TABLE Playlists (
  PlaylistID INT AUTO_INCREMENT PRIMARY KEY,
  UserID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Description TEXT,
  CreationDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Songs (
  SongID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(100) NOT NULL,
  Artist VARCHAR(50) NOT NULL,
  Album VARCHAR(50),
  Length INT,
  Genre VARCHAR(100)
);

CREATE TABLE PlaylistSongs (
  PlaylistID INT NOT NULL,
  SongID INT NOT NULL,
  Position INT NOT NULL,
  PRIMARY KEY (PlaylistID, SongID),
  FOREIGN KEY (PlaylistID) REFERENCES Playlists(PlaylistID),
  FOREIGN KEY (SongID) REFERENCES Songs(SongID)
);